### ISSUE TITLE
master breaks application broken with circular imports

### ISSUE THREAD

**Issue by cfra** [django-oauth/django-oauth-toolkit#1860]
I have a Django application that uses django-oauth-toolkit in conjunction with django-unfold.

I have custom admin classes like this:

```python
# project/admin.py

# Provide oauth2_provide admin classes with unfold admin,
# selection of admin classes is done in settings module.

from oauth2_provider.admin import (
    ApplicationAdmin as BaseApplicationAdmin,
    AccessTokenAdmin as BaseAccessTokenAdmin,
    GrantAdmin as BaseGrantAdmin,
    IDTokenAdmin as BaseIDTokenAdmin,
    RefreshTokenAdmin as BaseRefreshTokenAdmin
)
from unfold.admin import ModelAdmin

class ApplicationAdmin(BaseApplicationAdmin, ModelAdmin):
    pass

class AccessTokenAdmin(BaseAccessTokenAdmin, ModelAdmin):
    pass

class GrantAdmin(BaseGrantAdmin, ModelAdmin):
    pass

class IDTokenAdmin(BaseIDTokenAdmin, ModelAdmin):
    pass

class RefreshTokenAdmin(BaseRefreshTokenAdmin, ModelAdmin):
    pass
```

And reference these in my `project/settings.py` like this:

```python
# project/settings.py

# OIDC Provider
OAUTH2_PROVIDER = {
    "OIDC_ENABLED": True,
    "APPLICATION_ADMIN_CLASS": "project.admin.ApplicationAdmin",
    "ACCESS_TOKEN_ADMIN_CLASS": "project.admin.AccessTokenAdmin",
    "GRANT_ADMIN_CLASS": "project.admin.GrantAdmin",
    "ID_TOKEN_ADMIN_CLASS": "project.admin.IDTokenAdmin",
    "REFRESH_TOKEN_ADMIN_CLASS": "project.admin.RefreshTokenAdmin",
}   
```

This works fine in 3.4.1 but it fails in master with the following circular import:

 <details>
<summary>Backtrace</summary>

```
[2026-09-23 11:21:48 +0200] [284589] [INFO] Starting gunicorn 23.0.0
[2026-09-23 11:21:48 +0200] [284589] [INFO] Listening at: http://127.0.0.1:8000 (284589)
[2026-09-23 11:21:48 +0200] [284589] [INFO] Using worker: uvicorn_worker.UvicornWorker
[2026-09-23 11:21:48 +0200] [284598] [INFO] Booting worker with pid: 284598
/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/google/genai/types.py:42: DeprecationWarning: '_UnionGenericAlias' is deprecated and slated for removal in Python 3.17
  VersionedUnionType = Union[builtin_types.UnionType, _UnionGenericAlias]
[2026-09-23 11:21:55 +0200] [284598] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/user/coding/django-oauth-toolkit/oauth2_provider/settings.py", line 353, in import_from_string
    return import_string(val)
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/home/user/.pyenv/versions/3.14.2/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/home/user/company/my-application/project/admin.py", line 49, in <module>
    from oauth2_provider.admin import (
    ...<5 lines>...
    )
ImportError: cannot import name 'ApplicationAdmin' from partially initialized module 'oauth2_provider.admin' (most likely due to a circular import) (/home/user/coding/django-oauth-toolkit/oauth2_provider/admin.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
    ~~~~~~~~~~~~~~^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/home/user/.pyenv/versions/3.14.2/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/home/user/company/my-application/project/asgi.py", line 22, in <module>
    django_application = get_asgi_application()
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/django/core/asgi.py", line 12, in get_asgi_application
    django.setup(set_prefix=False)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
    ~~~~~~~~~~~~~~~~^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/django/contrib/admin/__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/my-application-lxhEWLcr-py3.14/lib/python3.14/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.14.2/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/home/user/coding/django-oauth-toolkit/oauth2_provider/admin.py", line 13, in <module>
    from oauth2_provider.authorization_server import admin as _moved
  File "/home/user/coding/django-oauth-toolkit/oauth2_provider/authorization_server/admin.py", line 282, in <module>
    application_admin_class = get_application_admin_class()
  File "/home/user/coding/django-oauth-toolkit/oauth2_provider/models.py", line 1385, in get_application_admin_class
    application_admin_class = oauth2_settings.APPLICATION_ADMIN_CLASS
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/coding/django-oauth-toolkit/oauth2_provider/settings.py", line 410, in __getattr__
    val = perform_import(val, attr)
  File "/home/user/coding/django-oauth-toolkit/oauth2_provider/settings.py", line 342, in perform_import
    return import_from_string(val, setting_name)
  File "/home/user/coding/django-oauth-toolkit/oauth2_provider/settings.py", line 356, in import_from_string
    raise ImportError(msg)
	ImportError: Could not import 'project.admin.ApplicationAdmin' for setting 'APPLICATION_ADMIN_CLASS'. ImportError: cannot import name 'ApplicationAdmin' from partially initialized module 'oauth2_provider.admin' (most likely due to a circular import) (/home/user/coding/django-oauth-toolkit/oauth2_provider/admin.py).
	[2026-09-23 11:21:55 +0200] [284598] [INFO] Worker exiting (pid: 284598)
```
</details>

**Version**

With git bisect, I found commit 33512b7f13e4696c23fdef12224337f864f63f27 to be the culprit.

**Comment by cfra** [comment]
I could resolve this for me with the following change of the import:

```diff
diff --git a/project/admin.py b/project/admin.py
index 148a892..f27de78 100644
--- a/project/admin.py
+++ b/project/admin.py
@@ -46,7 +46,7 @@ class TokenAdmin(BaseTokenAdmin, ModelAdmin):
 # Provide oauth2_provide admin classes with unfold admin,
 # selection of admin classes is done in settings module.
 
-from oauth2_provider.admin import (
+from oauth2_provider.authorization_server.admin import (
     ApplicationAdmin as BaseApplicationAdmin,
     AccessTokenAdmin as BaseAccessTokenAdmin,
     GrantAdmin as BaseGrantAdmin,
```

While this fixes the issue for me, I am not sure if there isn't still a bug, as I understood that the upcoming release is supposed to deprecate the old modules, but still allow their use, instead of breaking in unexpected ways.
